import { LitElement } from "lit-element";
import SettingsCard from "./components/settings/settings";
import { AnnotationData, Annotation, Manifest } from "./types/annotations";
import { ModelViewer } from "@google/model-viewer";
export default class HbllModelViewerElementBase extends LitElement {
    readonly modelViewer?: ModelViewer;
    readonly settings?: SettingsCard;
    readonly downloader?: any;
    readonly drawer_element?: any;
    readonly fullscreen_btn?: any;
    src: string | null;
    annotation_src: string | null;
    skybox_image: string | null;
    annotations: AnnotationData | null;
    edit: boolean | undefined;
    cameraIsDirty: boolean;
    currentAnnotation: Annotation | undefined;
    buttonStyles: any;
    files: Map<string, string>;
    manifest: Manifest | null;
    show_settings: boolean;
    showAnnotations: boolean;
    show_edit: boolean;
    show_dimensions: boolean;
    add_annotation_mode: boolean;
    annotation_list: Array<Annotation>;
    second_updated: boolean;
    loading: boolean;
    downloading: boolean;
    show_background: boolean;
    light_model_from_env: boolean;
    constructor();
    updated(changedProperties: any): void;
    firstUpdated(): Promise<void>;
    private onDragover;
    private onDrop;
    private handleClick;
    private saveAnnotations;
    private saveCameraOrbit;
    private annotationClick;
    private no_model_msg;
    private nav_label;
    private nextAnnotaion;
    private previousAnnotaion;
    static get styles(): import("lit-element").CSSResult[];
    private stringToHtml;
    private getAnnotationDescription;
    private toggleFullscreen;
    private isFullscreen;
    private change_name;
    render(): import("lit-element").TemplateResult;
    private change_annotation_color;
    private remove_annotation;
    private download_project;
    private change_index;
    private on_model_load;
    private render_dimensions;
}
