import { LitElement } from "lit-element";
import SettingsCard from "./components/settings";
import { AnnotationData, Annotation, Manifest } from "./types/annotations";
import { ModelViewer } from "@google/model-viewer";
export default class HbllModelViewerElementBase extends LitElement {
    readonly modelViewer?: ModelViewer;
    readonly settings?: SettingsCard;
    readonly downloader?: any;
    readonly drawer_element?: any;
    readonly fullscreen_btn?: any;
    src: string | null;
    annotation_src: string | null;
    skybox_image: string | null;
    annotations: AnnotationData | null;
    manifest_src: string | null;
    cameraIsDirty: boolean;
    currentAnnotation: Annotation | undefined;
    buttonStyles: any;
    files: Map<string, string>;
    manifest: Manifest | null;
    show_settings: boolean;
    showAnnotations: boolean;
    constructor();
    firstUpdated(): Promise<void>;
    private onDragover;
    private onDrop;
    private handleClick;
    private cameraMoved;
    private saveAnnotations;
    private saveCameraOrbit;
    private annotationClick;
    private no_model_msg;
    private nav_label;
    private nextAnnotaion;
    private previousAnnotaion;
    static get styles(): import("lit-element").CSSResult[];
    private stringToHtml;
    private getAnnotationDescription;
    private toggleFullscreen;
    private isFullscreen;
    render(): import("lit-element").TemplateResult;
}
